/* The nine district vaults.
 *
 * Stock OpenZeppelin ERC4626, so Deposit and Withdraw are the canonical
 * events and nothing here special-cases this game. The one addition is
 * Remitted: the oracle moving CityUSD out when a district has lost value.
 * A gain needs no event at all - the oracle simply transfers tokens in and
 * totalAssets() rises on its own - which is why Transfer is also handled.
 */
import { Address, BigInt } from '@graphprotocol/graph-ts';
/* graph codegen emits one module per data source, so nine byte-identical
   copies of the DistrictVault bindings exist. vault-abi.ts is generated by
   build-manifest.js and re-exports whichever one is first, so this handler
   stays one file and no district key is hardcoded here. */
import { Deposit, Withdraw, Transfer, Remitted } from './vault-abi';
import { VaultEvent } from '../generated/schema';
import { getVault, getPosition, repriceVault, eventId, ZERO } from './shared';

export function handleDeposit(e: Deposit): void {
  let v = getVault(e.address);
  v.totalAssets = v.totalAssets.plus(e.params.assets);
  v.totalShares = v.totalShares.plus(e.params.shares);
  v.depositedTotal = v.depositedTotal.plus(e.params.assets);
  repriceVault(v);
  v.save();

  /* owner, not sender. ERC-4626 lets one address deposit on another's behalf,
     and the position belongs to whoever ends up holding the shares. */
  let p = getPosition(e.params.owner, v, e.block.timestamp);
  p.shares = p.shares.plus(e.params.shares);
  p.depositedAssets = p.depositedAssets.plus(e.params.assets);
  p.updatedAt = e.block.timestamp;
  p.save();

  let ev = new VaultEvent(eventId(e));
  ev.vault = v.id;
  ev.kind = 'DEPOSIT';
  ev.account = e.params.owner;
  ev.assets = e.params.assets;
  ev.shares = e.params.shares;
  ev.assetsAfter = v.totalAssets;
  ev.block = e.block.number;
  ev.timestamp = e.block.timestamp;
  ev.tx = e.transaction.hash;
  ev.save();
}

export function handleWithdraw(e: Withdraw): void {
  let v = getVault(e.address);
  v.totalAssets = v.totalAssets.minus(e.params.assets);
  v.totalShares = v.totalShares.minus(e.params.shares);
  v.withdrawnTotal = v.withdrawnTotal.plus(e.params.assets);
  repriceVault(v);
  v.save();

  let p = getPosition(e.params.owner, v, e.block.timestamp);
  p.shares = p.shares.minus(e.params.shares);
  p.withdrawnAssets = p.withdrawnAssets.plus(e.params.assets);
  p.updatedAt = e.block.timestamp;
  p.save();

  let ev = new VaultEvent(eventId(e));
  ev.vault = v.id;
  ev.kind = 'WITHDRAW';
  ev.account = e.params.owner;
  ev.assets = e.params.assets;
  ev.shares = e.params.shares;
  ev.assetsAfter = v.totalAssets;
  ev.block = e.block.number;
  ev.timestamp = e.block.timestamp;
  ev.tx = e.transaction.hash;
  ev.save();
}

/* Shares moved directly, holder to holder. Mints and burns arrive here too and
 * are skipped, because Deposit and Withdraw have already counted them - double
 * counting a mint is the classic way a 4626 subgraph ends up with more shares
 * than the contract has. */
export function handleTransfer(e: Transfer): void {
  if (e.params.from == Address.zero() || e.params.to == Address.zero()) return;
  if (e.params.value.equals(ZERO)) return;

  let v = getVault(e.address);
  let from = getPosition(e.params.from, v, e.block.timestamp);
  from.shares = from.shares.minus(e.params.value);
  from.updatedAt = e.block.timestamp;
  from.save();

  let to = getPosition(e.params.to, v, e.block.timestamp);
  to.shares = to.shares.plus(e.params.value);
  to.updatedAt = e.block.timestamp;
  to.save();
}

/* The loss path. remit() is the only way assets leave without a withdrawal,
 * and the contract caps it at 5% of the vault per settlement - so a bad term
 * visibly hurts but cannot empty the vault in one transaction. */
export function handleRemitted(e: Remitted): void {
  let v = getVault(e.address);
  v.totalAssets = e.params.assetsAfter;
  v.settledTotal = v.settledTotal.minus(e.params.amount);
  repriceVault(v);
  v.save();

  let ev = new VaultEvent(eventId(e));
  ev.vault = v.id;
  ev.kind = 'REMIT';
  ev.account = null;
  ev.assets = e.params.amount;
  ev.shares = ZERO;
  ev.assetsAfter = e.params.assetsAfter;
  ev.block = e.block.number;
  ev.timestamp = e.block.timestamp;
  ev.tx = e.transaction.hash;
  ev.save();
}
